### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by jovan4981** [ikedam/backend-update-center2#20]
As i tried to point out on jenkins users...
(https://groups.google.com/forum/#!topic/jenkinsci-users/J0n8zIkAsQo)

Exception Hadnling is rather ugly. As we're running our jenkins in a subnet without access to www, i was wondering if it's possible to create an update center on my own. And voila: I found your solution.

But:
Since some of manifest files are corrupted on plug-in repository we actually cloned to access localy, i found that exception handling is to be reworked.

It's not a big deal....

**Comment by ikedam** [comment]
Same issue to #16.
