### ISSUE TITLE
/latest subdirectory is not populated

### ISSUE THREAD

**Issue by robled** [ikedam/backend-update-center2#21]
While the update center output data is still usable by Jenkins, the symlinks that are supposed to be in the /latest directory of the update center web directory are not populated and the directory is empty.  

Steps to reproduce:

* Run the following command or similar to generate an update center:

```
/usr/bin/mvn -e exec:java -Dexec.args="\
    -id "$update_center_id"\
    -hpiDirectory /var/opt/update-center/"$package_dir"/\
    -key /file.key\
    -certificate /file.crt\
    -root-certificate /file.crt\
    -www "$web_dir"/"$package_dir"\
    -download "$web_dir"/"$package_dir"/download\
    -repository http://example.com/"$package_dir"\
    -includeSnapshots\
    -pretty"
```

*  Check the /latest subdirectory on your webserver.  It should be empty.

**Comment by ikedam** [comment]
Not a defect.
The /latest is handled with .htaccess.
Please put the .htaccess on your web server, or use plugins/(artifactname)/latest symlink instead.

**Comment by robled** [comment]
Thanks for the guidance, I'll make the changes as described.
